title: MeSPhA
description: Medical Statistics, Philosophy and Arts
author: MeSPhA
#email: acallegaro@gsk.com
#phone: (650) 576-5403
#github: https://github.com/tmjam
#about: Open-access cross-disciplinary online magazine
disqus_shortname: Medical Statistics
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

# social:
   # - icon: fa-facebook
   #  link: "https://www.facebook.com/tjamadar"
   # - icon: fa-twitter
   #   link: "https://twitter.com/tmjam3011"
   #- icon: fa-linkedin
   #  link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
    # - icon: fa-stack-exchange
    #   link: "#"
  #  - icon: fa-github
  #    link: "https://github.com/tmjam"

#share:
 # twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About the Magazine
      url: /about/
    - text: Publications
      url: /projects/
    - text: Blogs
      url: /blogs/
   # - text: XML Feed
   #   url: /feed.xml
# url: "http://localhost:4000"
#url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
