title: MeSPhA
description: Medical Statistics, Philosophy and Arts (MeSPhA)
disqus_shortname: Cross-disciplinary open-access-online magazine
#google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

#url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
